version: "3.6"

services:
  db:
    image: postgres:latest
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432  
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=<%= ENV['POSTGRES_USER_DEV'] %>
      - POSTGRES_PASSWORD=<%= ENV['POSTGRES_PW_DEV'] %>
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - db
    ports:
      - "5555:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: <%= ENV['PGADMIN_EMAIL_DEV'] %>
      PGADMIN_DEFAULT_PASSWORD: <%= ENV['DATABASE_PW_PROD'] %>
    restart: unless-stopped
volumes:
  pgdata: